// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
#[derive(Queryable, Debug)]
pub struct Bot {
    pub id: String,
    pub team_id: String,
    pub version: String,
    pub created: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Competition {
    pub id: String,
    pub name: String,
    pub start: String,
    pub end: String,
    pub allowed_submissions: String,
    pub round: String,
    pub type_: String,
    pub created: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Games2v2 {
    pub id: String,
    pub competition_id: String,
    pub round: String,
    pub team1_id: String,
    pub team2_id: String,
    pub team1bot1_id: String,
    pub team1bot2_id: String,
    pub team2bot1_id: String,
    pub team2bot2_id: String,
    pub team1bot1_survived: bool,
    pub team1bot2_survived: bool,
    pub team2bot1_survived: bool,
    pub team2bot2_survived: bool,
    pub log_file_path: String,
    pub public: bool,
    pub additional_data: String,
    pub created: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Team {
    pub id: String,
    pub owner: String,
    pub partner: String,
    pub competition_id: String,
    pub bot1: String,
    pub bot2: String,
    pub created: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: String,
    pub student_number: String,
    pub ldap_dn: String,
    pub created: NaiveDateTime,
}

